### ISSUE TITLE
Cannot access https://hub.ipcc.ifca.es/thredds 

### ISSUE THREAD

**Issue by Yefee** [zequihg50/eva#1]
Nice package! I now found the https://hub.ipcc.ifca.es/thredds is no longer accessible.

**Comment by zequihg50** [comment]
It should be accessible although the certificate has expired, I'm waiting for IT to send a new certificate. You may try to access through a private browser window or remove your browser cache for https://hub.ipcc.ifca.es (this way you can tell the browser to trust the website regardless of the expired certificate).

**Comment by zequihg50** [comment]
@Yefee The certificate has been updated, the server should be working again.

**Comment by Yefee** [comment]
Thanks! It works now!
